### ISSUE TITLE
Unable to maximize WebRTC streams in lovelace

### ISSUE THREAD

**Issue by HITChris** [AlexxIT/WebRTC#87] opened 2021-06-09 20:00 UTC
Worked fine prior to the latest release. HA error -

![a](https://user-images.githubusercontent.com/34664460/121421269-9bd6e900-c933-11eb-80bf-69ce62e711e7.PNG)

**Comment by maxcanna** [comment] 2021-06-11 17:23
Duplicate of #84

**Comment by Zagor4** [comment] 2021-06-12 08:26
I have the same problem !

**Comment by maxcanna** [comment] 2021-06-12 08:27
> I have the same problem !

please @Zagor4 avoid to answer with "me too". Just +1 the OP so the maintainer can know it affects multiple people 🙂

**Comment by Zagor4** [comment] 2021-06-12 09:10
> > I have the same problem !
> 
> please @Zagor4 avoid to answer with "me too". Just +1 the OP so the maintainer can know it affects multiple people 🙂

Sorry... :(
What i have to do, to put +1 ?

**Comment by maxcanna** [comment] 2021-06-12 09:11
> Sorry... :(
> What i have to do, to put +1 ?

No worries, just put a 👍🏻  reaction as you just did. But in the original issue since this is even a duplicate 😉

**Comment by AlexxIT** [comment] 2021-06-16 14:10
Thanks @idoaflalo! Fixed in latest release

**Closed by AlexxIT** 2021-06-16 14:10 UTC
