### ISSUE TITLE
webrtc broken after update to core 2022.7

### ISSUE THREAD

**Issue by Claudio1L** [AlexxIT/WebRTC#321] opened 2022-07-07 05:47 UTC
after update to 2022.7, logged "login attempt failed"

**Comment by sesardelaisla** [comment] 2022-07-07 06:25
I don’t see WebRTC video feed in dashboard either after updating HA to 2022.7.0. However, I cannot see MotionEye cameras in dashboard too, despite they are displayed in MotionEye config. I think this is an issue related to how the cameras are handled in dashboards in the new HA version, not with WebRTC or MotionEye integrations themselves. Just saying in case it gives a clue about where the problem is.

**Comment by gody01** [comment] 2022-07-07 07:05
+1

**Comment by fotis3d** [comment] 2022-07-07 08:18
+1 here. I get Login failed. Though the same rtsp in VLC works just fine.

**Comment by aljubori** [comment] 2022-07-07 08:19
Same here after upgrading to 2022.7.0.

**Comment by edwRoland** [comment] 2022-07-07 08:23
+1 same here

**Comment by pickonedev** [comment] 2022-07-07 09:11
Same problem, login failed, ban ip :-)

**Comment by sesardelaisla** [comment] 2022-07-07 09:39
Just in case it helps, I just realized that MotionEye cameras started working again in dashboards. However, WebRTC cameras don't, so it seems the issue is related to some sort of HA Core 2022.7.0 - WebRTC compatibility issue. I have read somewhere that it could be related to the fact that python version was updated in HA Core 2022.7.0, so it might be needed to update WebRTC accordingly.

**Comment by miit86** [comment] 2022-07-07 10:46
same as #318

**Comment by Claudio1L** [comment] 2022-07-07 11:07
> same as #318 also you can use the fix in #318

not working for me. For this reason opened another bug

**Comment by Claudio1L** [comment] 2022-07-07 12:00
The only point I don't understand is the following: I have no reference related to IP_Ban in the configuration.yaml Have to add something?

**Comment by miit86** [comment] 2022-07-07 12:06
@Claudio1L 

did you clear the cache on your android or browser?
no if you don't use the ipban in you config. you dont have to do anyhting

**Comment by Claudio1L** [comment] 2022-07-07 12:08
Yes, cleared everything, used different browsers from my Mac. Nothing

**Comment by miit86** [comment] 2022-07-07 12:09
hmmzz, I havent got a mac, so I can't test it for you.
do you have a windows PC or an Android device. and test it?

**Comment by Claudio1L** [comment] 2022-07-07 12:17
Same from a windows vm

**Comment by Claudio1L** [comment] 2022-07-07 12:22
Anyway thanks @miit86 for your effort. Let's wait for a consolidated fix

**Comment by miit86** [comment] 2022-07-07 12:48
oke, did you remove the pycache from folder: \config\custom_components\webrtc

**Comment by DT00689** [comment] 2022-07-07 14:00
I replaced the webrtc-camera.js file, removed the pycache folder, restarted HA, cleared browser cache. Still getting the same issue. Feed says restart connection after a few seconds

**Comment by lexstoj** [comment] 2022-07-07 14:47
where do i find webrtc-camera.js file?

**Comment by vmakeev** [comment] 2022-07-07 15:12
@Claudio1L try to remove special characters from camera's login/password (if exists). It works for me

**Comment by Gferretta** [comment] 2022-07-07 16:28
Do not work for me after 2022.07

**Comment by freirejc** [comment] 2022-07-07 17:46
+1

**Comment by robertoleonardo** [comment] 2022-07-07 17:55
+1

**Comment by canuckray** [comment] 2022-07-07 18:13
for what it's worth..... +1

**Comment by Koendejongh** [comment] 2022-07-07 20:08
another +1 here

**Comment by canuckray** [comment] 2022-07-07 20:21
I rolled back while a solution is worked on (I tried the workarounds discussed, but had no success).

On a positive note, I'm happy to report that Home Assistant backup rollback functionality works awesome!  Haha

**Comment by vmakeev** [comment] 2022-07-07 21:59
> was working from 3 month at least. Why should login/password be corrupted now?

Double URL encoding I think

**Comment by VolkerLaude** [comment] 2022-07-08 05:22
+1

**Comment by WMWong78** [comment] 2022-07-08 07:47
+1 rolled back to previous HA version and working again.

**Comment by Murder3D** [comment] 2022-07-08 08:31
+1, after the last HA update it isn't working anymore.

It doesn't load the stream from a Windows PC running Chrome.
It doesn't load the stream from the iOS Companion App.
It doesn't load the stream from Fully Kiosk Browser running on a tablet.

Getting the same error on every device I use:

Login attempt failed
Login attempt or request with invalid authentication from blablabla (192.168.1.xxx). See the log for details.

**Comment by MRBetes** [comment] 2022-07-08 08:34
Same problem, 
- cameras working fine
- update from core 2022.6.7 to 2022.7
- Cameras not working anymore (restart connection message) (tried another browser, anbother device, restart homeassistant)
- Restore 2022.6.7
- cameras working fine

**Comment by dandanarsk** [comment] 2022-07-08 08:38
Strange that this happens same time as the camera authorisation problems from Synology DSM... [#74630](https://github.com/home-assistant/core/issues/74630)

**Comment by Koendejongh** [comment] 2022-07-08 08:45
Also reolink camera issues with 2022.7 HA.
 https://github.com/fwestenberg/reolink_dev/issues/525#issue-1290622078

**Comment by Claudio1L** [comment] 2022-07-08 10:19
after update to core 2022.7.1 Cameras are working again without touching anything!
I left there all the fix from https://github.com/AlexxIT/WebRTC/pull/320/commits, I haven't tried without them because I don't want to touch anything now that is working.

![immagine](https://user-images.githubusercontent.com/97904190/177973618-d9aa85c8-1f03-4267-9304-4d911da67cab.png)

**Comment by miit86** [comment] 2022-07-08 10:21
@Claudio1L 

would you mind to check the version of "webrtc-camera.js" you have.
is it the patched one or the original?

Just Curious, because after an update the cache is cleared.

**Comment by Claudio1L** [comment] 2022-07-08 10:27
not clear where to check the version of "webrtc-camera.js". I don't see any "version" field inside the file. It should be the orgiginal with applied the fixes from https://github.com/AlexxIT/WebRTC/pull/320/commits

I deleted __pycache__ content multiple times during testing yersterday

**Comment by Claudio1L** [comment] 2022-07-08 10:39
unfortunately, from iphone the issue is still there
![WhatsApp Image 2022-07-08 at 12 35 28](https://user-images.githubusercontent.com/97904190/177976795-d6afc649-24c6-4bea-8487-07012c27cfed.jpeg)
.

**Comment by mariusnauj** [comment] 2022-07-08 10:54
Tryied reinstall WebRTC, confgure from new, bet result the same still not working.

**Comment by J0nnyBr4v0** [comment] 2022-07-08 11:20
same here. 
have also ip bans activated and due to connection fails to the cams. HA also bann all my clients which tries to load the lovelace view.
`http:
  ip_ban_enabled: true
  login_attempts_threshold: 4
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1`

**Comment by Gferretta** [comment] 2022-07-08 11:47
> @Claudio1L did you follow the steps?
> it is the same bug..! 
> 
> I've tested it on android, edge, chrome and an old android (had to clear cache and reboot)
> tested from LAN and WAN both fully functional with Sound. 
> when you use ip-ban make sure you don't open the stream until you cleared the cache, else it will put your ip on the list.
> 
> 1. you have to replace "webrtc-camera.js"
> 2. remove the pycache from the webrtc folder
> 3. clear the cache from HA app in android.
> 4. clear browsing data in chrome/edge.
> 
> 

This hack work perfectly in 2022.7.0 also 2022.7.1
Thanks

**Comment by harambe88** [comment] 2022-07-08 12:04
Same here: no stream, but Frigate NVR is recording video and clips.

**Comment by mariusnauj** [comment] 2022-07-08 12:10
For me this hack not working always appearing message restart connection.

**Comment by DT00689** [comment] 2022-07-08 12:13
Hack did not work for me in 7.0 or 7.1

**Comment by Gferretta** [comment] 2022-07-08 14:24
> just replaced the webrtc-camera.js from the latest commit and restarted, get the exact same issue. running 2022.7.1

Not "only replaced"
All the step and order are important and then all cameras working fine!

**Comment by dreimer1986** [comment] 2022-07-08 14:32
Pull confirmed working perfectly. I am on 2022.7.1 by now, too btw. And no, it does NOT work without it. Even on .1 version.

```
2webrtc-camera.js?v2.3.0:123 Received MSE codecs: avc1.640020
2webrtc-camera.js?v2.3.0:133 Received WebRTC SDP
2webrtc-camera.js?v2.3.0:239 WebRTC state: connecting
2webrtc-camera.js?v2.3.0:211 Connecting over WAN
2webrtc-camera.js?v2.3.0:239 WebRTC state: connected
4webrtc-camera.js?v2.3.0:155 Auto seek to livetime
2webrtc-camera.js?v2.3.0:179 Switch to WebRTC
```

**Comment by thefunkygibbon** [comment] 2022-07-08 15:15
> > just replaced the webrtc-camera.js from the latest commit and restarted, get the exact same issue. running 2022.7.1
> 
> Not "only replaced" All the step and order are important and then all cameras working fine!

yes, i deleted the pycache contents and tried it on a fresh browser that hasn't used it before etc.  still not having it.

**Comment by Claudio1L** [comment] 2022-07-08 17:18
Solved the iphone issue with a couple of frontend cache cleaning in the app. Next check will be android

**Comment by Murder3D** [comment] 2022-07-09 06:09
Is this custom integration still being developed/mantained?

**Comment by Vards0** [comment] 2022-07-09 06:47
Fix did not work for me either.

**Comment by harambe88** [comment] 2022-07-09 08:18
2022.7.2 is out - and didn't fix it.

**Comment by pickonedev** [comment] 2022-07-09 12:01
> Is this custom integration still being developed/mantained?

Yes, the integration it is still active, @AlexxIT It is doing a great job, but all we need is patience.
He just solved the Sonooff LAN issue (being in holiday), so I bet that he will save us with this problem too.

Cheers

**Comment by gdgeist** [comment] 2022-07-09 20:45
+1 on 7.1 and 7.2 - issue remains

**Comment by hugalafutro** [comment] 2022-07-10 04:04
I don't really understand the issue, but I think it might have to do with the ffmpeg version inside HA or something?
if I run ffmpeg "rtmp://blablalbla" I get info about the stream as expected, doing the same with "rtsp://blablabla" stream gives me errors like `Invalid data found when processing input` or `Unable to find a suitable output format for 'rtsp://blablabla`

Again, I'm not the most technical, I just remember when webrtc camera worked in HA, I could run ffmpeg with rtsp stream without error message. (Similar 3y old issue, where rtsp was broken in some versions of ffmpeg I found while googling here:https://github.com/acaudwell/Gource/issues/216).

I have tried the steps outlined #318 to no avail.

**Comment by harambe88** [comment] 2022-07-10 11:39
Went back to 2.6.7 and webRTC is working!

**Comment by subliminal1988** [comment] 2022-07-10 15:54
> @Claudio1L try to apply #320 and remove special characters from camera's login/password (if exists). It works for me. And change "version" at webrtc-camera.js file

FYI: Some cameras do not support a password without special chars.

**Comment by ibanmda** [comment] 2022-07-11 07:16
Doesn't work also in:

```
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest
```

**Comment by pepsonEL** [comment] 2022-07-11 11:41
> Doesn't work also in:
> 
> ```
> Home Assistant 2022.7.3
> Supervisor 2022.07.0
> Operating System 8.2
> Frontend 20220707.0 - latest
> ```

For me also no working

**Comment by Bod1985** [comment] 2022-07-11 12:15
Rather than commenting, please use the thumbs up feature if you only wish to confirm you’re also experiencing the issues, it isn’t productive and causes unnecessary notifications for subscribers.

**Comment by freirejc** [comment] 2022-07-12 00:04
Guys, see below what worked for me... Everything working fine now.

1. File Browser, change the file custom_components\webrtc\www[webrtc-camera.js] 
put below RAW code:
https://raw.githubusercontent.com/skrobul/WebRTC/38c77b400f86f20a42e0b8103bb01f6a0a7377eb/custom_components/webrtc/www/webrtc-camera.js

2. Delete the .gz file located in custom_components\webrtc\www

3. Delete all files located in custom_components\webrtc_pycache_

4. Remove IP Ban (in case you have it)

5. Restart you HA and in the meantime you clear all the cash from your browser. Do not forget to clear the cash in your mobile phone app as well.

6. Try to see your cameras in your browser and in your mobile app.

7. If everything is working fime, turn on IP Ban again.

**Comment by thefunkygibbon** [comment] 2022-07-12 10:15
> Guys, see below what worked for me... Everything working fine now.


Yup, that's what I did.  No dice.

**Comment by dandanarsk** [comment] 2022-07-12 11:29
Still not working here after trying those steps (except 2, had no .gz file in custom_components\webrtc\www folder)
No ip ban setup neither

**Comment by freirejc** [comment] 2022-07-12 11:37
Did you guys full clean up the browser cash?

**Comment by dandanarsk** [comment] 2022-07-12 11:58
> Did you guys full clean up the browser cash?

Using the HA as web app, after cleaning the cache in Chrome as well is working... tks

**Comment by AlexxIT** [comment] 2022-07-13 05:39
Fixed in latest release
https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.1

**Closed by AlexxIT** 2022-07-13 05:39 UTC
Labels: bug

**Comment by VolkerLaude** [comment] 2022-07-13 19:21
That works - Thanks
