### ISSUE TITLE
Invalid config - Can't start webrtc

### ISSUE THREAD

**Issue by webdados** [AlexxIT/WebRTC#282] opened 2022-03-28 14:15 UTC
I'm getting this notification after installing WebRTC and restarting HA.

Invalid config
The following integrations and platforms could not be set up:

[webrtc](https://github.com/AlexxIT/WebRTC)
Please check your config and [logs](https://192.168.1.252:8123/config/logs).

The logs say this:
`2022-03-28 14:52:24 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
(...)
2022-03-28 14:52:36 ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
utils.register_static_path(hass.http.app, url_path, path)
File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
app[allow_cors](route)`

Any ideas?

Home Assistant 2022.3.7
Operating System Version 5.10.92-v8

**Comment by johnjoemorgan** [comment] 2022-03-29 03:44
Getting the same issue after upgrading to the latest version

**Comment by Sarunas88** [comment] 2022-03-29 09:28
where do you find this error message ? i am trying to start WebRTC for 2 days now without any succes, perhaps i got the same issue

**Comment by moshiko2312** [comment] 2022-03-29 14:41
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 17:36:00 (1 occurrences)
Last logged: 17:36:00

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/_init_.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in _getitem_
    return self._state[key]
KeyError: 'allow_cors'

**Comment by fabiobrolo** [comment] 2022-03-30 12:37
I´m having the same issue

**Comment by fabiobrolo** [comment] 2022-03-30 12:48
Try to remove the integration, install master version, restart HA and configure the integration back.

**Comment by Sarunas88** [comment] 2022-03-30 12:49
https://github.com/AlexxIT/WebRTC/issues/278#issuecomment-1074448685

please do like here, everything is working fine.

**Comment by jscherry** [comment] 2022-03-31 03:13
Still not working after removing, restarting ha, then installing master version on 2022.4 beta? Can't load. With the newest regular version of webrtc will load but keep getting allow_cors?

**Comment by strasharo** [comment] 2022-04-01 19:26
Removed everything and pulled from master, still hitting allow_cors.

**Comment by interbiznw** [comment] 2022-04-03 12:10
getting this same error even after removing and installing master version.......any update????

**Comment by FirstRulez** [comment] 2022-04-08 17:05
I've only just installed this integration, and am also seeing this error. Any suggestions?

`2022-04-08 08:58:30 ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
utils.register_static_path(hass.http.app, url_path, path)
File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
app['allow_cors'](route)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
return self._state[key]
KeyError: 'allow_cors'`

**Comment by jopvanraaij** [comment] 2022-04-09 17:41
I have the same error, using

<details><summary>version | core-2022.4.1</summary>
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Europe/Amsterdam

</details>
<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4954
Installed Version | 1.24.3
Stage | running
Available Repositories | 1083
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 17.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Node-RED (11.1.1), WireGuard (0.6.0), Grafana (7.5.2), InfluxDB (4.4.1), Let's Encrypt (4.12.0), NGINX Home Assistant SSL proxy (3.1.1), Mosquitto broker (6.0.1), Z-Wave JS (0.1.55), Terminal & SSH (9.3.0), Eufy Security Add-on (0.8.4), RTSP Simple Server Add-on (v0.17.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>


Installed using WebRTC v2.1.0 HACS integration

**Comment by webdados** [comment] 2022-04-09 17:51
Is this project abandoned? I’m willing to contribute with a money compensation to have this problem fixed.

**Comment by jopvanraaij** [comment] 2022-04-09 17:59
I guess issue is a duplicate of #280, solved it, see my comment in #280

**Comment by AlexxIT** [comment] 2022-04-10 14:12
https://github.com/AlexxIT/WebRTC/issues/270#issuecomment-1064862905

**Closed by AlexxIT** 2022-04-10 14:12 UTC
Labels: duplicate
