### ISSUE TITLE
"muted: false" no longer working 

### ISSUE THREAD

**Issue by criticallimit** [AlexxIT/WebRTC#540] opened 2023-07-25 18:59 UTC
Don´t know since when the "muted" is no longer working, but no matter if muted is set to true or false, it´s always muted and has to be set in the card manually

```yaml
type: custom:webrtc-camera
url: rtsp://192.168.178.10:8554/Essen?video=all&audio=opus
ui: true
title: null
muted: false
background: false
intersection: 0.4
mode: webrtc
```

**Comment by stplatt** [comment] 2023-07-26 15:51
Duplicate of https://github.com/AlexxIT/WebRTC/issues/529

**Closed** 2023-08-24 04:14 UTC
Labels: duplicate

**Comment by 9F72-DCCA** [comment] 2026-04-19 18:23
Try this: It works for me.

 type: custom:webrtc-camera
 url: rtsp://....
 muted: false
 autoplay: true
 mode: webrtc
