### ISSUE TITLE
ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc

### ISSUE THREAD

**Issue by Asinke** [AlexxIT/WebRTC#278] opened 2022-03-19 17:25 UTC
I get below error when setting up webrtc.

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
utils.register_static_path(hass.http.app, url_path, path)
File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
app['allow_cors'](route)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
return self._state[key]
KeyError: 'allow_cors'

Home Assistant 2022.3.5

**Comment by pjuhl2313** [comment] 2022-03-20 13:46
I'm getting the same thing. Happened after I updated my HA last week.

**Comment by therealwave** [comment] 2022-03-21 21:28
Same here... Tried to install WebRTC through HACS.


Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera ([documentation](https://github.com/AlexxIT/WebRTC), [issues](https://github.com/AlexxIT/WebRTC/issues))
First occurred: 2:22:54 PM (1 occurrences)
Last logged: 2:22:54 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'


Version | core-2022.3.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.92-v8
CPU Architecture | aarch64
Timezone | America/Los_Angeles

**Comment by mick1988** [comment] 2022-03-21 21:41
Had the same issue. Followed the instructions here and it is now working for me:

https://github.com/AlexxIT/WebRTC/issues/270#issuecomment-1062623878

**Comment by mohannaddubagh** [comment] 2022-04-03 21:45
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 11:43:25 PM (1 occurrences)
Last logged: 11:43:25 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by jopvanraaij** [comment] 2022-04-09 17:59
I guess issue is a duplicate of #280, solved it, see my comment in #280

**Comment by AlexxIT** [comment] 2022-04-10 14:11
https://github.com/AlexxIT/WebRTC/issues/270#issuecomment-1064862905

**Closed by AlexxIT** 2022-04-10 14:11 UTC
Labels: duplicate
