### ISSUE TITLE
View on small browser widths and in Android mobile app shows 2 media player windows

### ISSUE THREAD

**Issue by timdonovanuk** [AlexxIT/WebRTC#142] opened 2021-10-15 14:59 UTC
![image](https://user-images.githubusercontent.com/8156439/137508648-c3db3a8a-8771-4378-88b7-8274d283b73b.png)

Ignore the stream error..this goes away eventually, but still, at small widths it shows two media windows. Here is a pic from the android app:

![image](https://user-images.githubusercontent.com/8156439/137508812-1bc6186d-81ca-4448-b7bc-759a7c416cdd.png)

My configuration is simply:

```
type: custom:webrtc-camera
url: rtsp://admin:password@192.168.1.10:554//h264Preview_01_main
ui: true
view_layout:
  position: main

```

**Comment by sisao** [comment] 2021-11-11 18:27
Look like on small displays component renders twice..
![image](https://user-images.githubusercontent.com/514609/141349997-c9263ced-4750-4a50-beac-22e564d49ac0.png)

**Comment by sisao** [comment] 2021-11-12 12:58
I did a little debugging and I think it's a HACS related issue, when the component gets deployed...
I have installed the latest version via HACS 2.1.1.
But I see a refence to version 2.0.2 in the file loaded in browser like webrtc-camera?v2.0.2 and also in the file  .storage/lovelace_resources:  "url": "/webrtc/webrtc-camera.js?v2.0.2".
I edited this file and set v2.1.1 and the double rendered issue disappears.

**Comment by sisao** [comment] 2021-11-12 13:14
I replaced webtrc-camera.js with the current one from master branch, and the issue is gone.
I think this commit https://github.com/AlexxIT/WebRTC/commit/4d05f936f72ac87b56e71785a169a86971401e98#diff-1789d1e296c9412df25cd916f3b2efb332f9e55b1caa948ae1252ffd3eb5cb9a fixes it.

**Comment by AlexxIT** [comment] 2022-04-10 12:55
I think this is fixed in latest version

**Closed by AlexxIT** 2022-04-10 12:55 UTC
Labels: bug
