### ISSUE TITLE
Android webrtc stream often doesn't play

### ISSUE THREAD

**Issue by cliffjao** [AlexxIT/WebRTC#28] opened 2021-04-22 16:26 UTC
In the Android HA app, streams get into "Connected" state but fail to actually play about 50% of the time. Quitting the app and then coming back eventually will get it to work. On desktop Chrome, it seems to be 100% reliable.

![Screenshot_20210422-092425](https://user-images.githubusercontent.com/5115073/115750118-ad950a80-a34c-11eb-854c-758704ecd719.png)

**Comment by cliffjao** [comment] 2021-04-22 16:31
This also seems to happen on mobile Chrome, so maybe it's an Android issue?

**Comment by AlexxIT** [comment] 2021-04-28 07:44
At this point, the browser tries to load the video stream. Problems often depend on the specific camera

**Comment by derwolff** [comment] 2021-04-29 06:03
I also noticed this issue with an Android Tablet and newer versions of webrtc. 
With version 1.4.0 also the app fully kiosk browser crashes after some minutes if the stream is not displayed.

**Comment by AlexxIT** [comment] 2021-04-29 14:01
Maybe tablet performance is not enough for this technology

**Comment by derwolff** [comment] 2021-04-29 14:42
It's not a powerful tablet but sufficient for wall mounting. I revert to version 1.1.0 which is working.

**Comment by AlexxIT** [comment] 2021-04-29 18:31
Can you check 1.2 and 1.3?

**Comment by derwolff** [comment] 2021-04-30 05:46
1.2 is working. Now I try 1.3 but as I know here starts the issue that the stream is not showen in all cases but doesn't crash the fully kiosk browser.

**Comment by AlexxIT** [comment] 2021-04-30 09:04
What model is your tablet?

**Comment by derwolff** [comment] 2021-04-30 09:41
LIFETAB_P733X (LENOVO), Android version 5.0.2 (SDK 21). It was not so easy to find a tablet which looks similar to an GIRA G1 Controller ;-) .

**Comment by derwolff** [comment] 2021-05-01 10:29
Version 1.3.0 also works since yesterday.

**Comment by tunerooster** [comment] 2021-05-02 15:21
Ditto...  I am experiencing this on every platform.  My Android tablets are powerful, and I see the same issue on my PC.  All instances are via Chrome browser.

It seems more frequent when I switch around between several cameras.

Are the connections being closed when views are not visible, and re-opened when they become visible?

For me, the problem is also more frequent over wifi than over ethernet (eg, on my PC).  Even if it is network traffic related, is it possible to be more aggressive about closing and reconnecting the stream when is pauses/disconnects (eg, more robust)?

It is still a great improvement over HA builtin streaming!!!

**Comment by playersct** [comment] 2021-05-08 10:55
![Screenshot_20210508-124919_Home Assistant 1](https://user-images.githubusercontent.com/6294263/117536603-33c37900-affc-11eb-9075-a1701745f568.jpg)

I have another problem on my Galaxy S20 with official Home Asistant app. This is what i see. On Xiaomi Redmi Note 8 Pro all is ok. Do you have any idea what's wrong?

**Closed** 2023-01-20 18:25 UTC
Labels: bug
