### ISSUE TITLE
Not working after update UniFi Protect

### ISSUE THREAD

**Issue by shgubar** [AlexxIT/WebRTC#305] opened 2022-05-27 17:05 UTC
Hi
Today I made an update to UniFi Protect from version 1.21.6 to 2.0.0. 
After that, your component stopped working.
At the moment I use the web version of the camera 2.3.0.
i'm trying with 2.2.0 - same issue.
The screen displays "Error: EOF", starts the restart and again the same - a dark screen.

**Comment by shgubar** [comment] 2022-05-27 18:38
I forgot to write about the **error** in the browser (_Chrome's Developer Tools_):

<img width="363" alt="Screenshot 2022-05-27 at 21 35 27" src="https://user-images.githubusercontent.com/75221402/170770727-fdefceeb-c0a0-4e83-8334-45c749756570.png">

**Comment by pghattas** [comment] 2022-05-29 17:02
I seem to be having the same issue

**Comment by danthel** [comment] 2022-05-30 14:00
Same issue, would be nice with an update or workaround.
Seems Ubiquiti added a 2nd audio stream, see attached screenshot.

![codec info](https://user-images.githubusercontent.com/89740002/171007882-6bcc4741-221e-45d3-8e77-1406a89bc8ff.jpg)

**Comment by writemike** [comment] 2022-05-30 23:57
Same issue as well. Please let me know if there is anymore detail I can provide to help troubleshoot. Really regret updating Unifi Protect...

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
WebRTC Camera 2.3.0
Unifi Protect 2.0.0
Cameras: G4 Dome and G4 Doorbell (Firmware Version 4.51.14)

home-assistant.log error:

> 2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/31 09:17:03 Stream Try Connect rtsp://192.168.10.55:7447/i9VQ4hpe19mEhTwk
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/31 09:17:03 Stream Try Connect rtsp://192.168.10.55:7447/BcpyYHzfm6vR1KXM
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 33 [running]:
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0xc0000b9900, 0x201, 0xf4240, 0x1558f03f8500, 0x3ef1480, 0xc0002f6000, 0x8c73, 0xa000, 0x400, 0xc000280d60, ...)
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 	C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x425
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0xc0000f6e10, 0xc0002391cc, 0x2a)
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x89e
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x454
2022-05-31 09:17:03 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/31 09:17:03 Server Start Awaiting Signal

**Comment by Boromore** [comment] 2022-05-31 12:15
I'm also having this issue.
Webrtc keeps restarting connection in Home Assistant.

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
WebRTC Camera 2.3.0
Unifi Protect 2.0.0
Cameras: G4 bullet (4x) and G4 Doorbell (all at Firmware Version 4.51.14)

**Comment by MuttzNuttz** [comment] 2022-06-01 18:20
I am also having the same issue since Unifi Protect was updated to V2.0.0

Home Assistant Core 2022.6.0
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
WebRTC Camera 2.3.0

Cameras affected G2 Bullet, G3 Bullet, G3 Flex, G3 Instant, G4 Doorbell, G4 Bullet.

**Comment by shgubar** [comment] 2022-06-03 07:36
FYI: Protect 2.0.1 does not fixed RTSP stream.

**Comment by stubble0seven** [comment] 2022-06-03 20:15
Same issue here, trying an Early Release update to Protect now

**Comment by pghattas** [comment] 2022-06-04 11:55
FYI I was able to downgrade to unifi protect 1.21.6 and I disabled auto update in the unifi console and I have webrtc working again

PLEASE BE aware you will lose your recordings and settings, so you need to have a backup prior to 2.0. USE AT your own risk!!!

Here are the steps;

Login via ssh
goto the shell
Remove Protect completely
reinstall protect


- unifi-os shell

- apt purge unifi-protect 

- apt-get update

- apt-get install unifi-protect=1.21.6

**Comment by danthel** [comment] 2022-06-04 15:02
> 

The issue isn't Protect really, they're compliant with RTSP afaik.
What they did is to add a 2nd audio stream, clients utilizing the stream need to add support for that.

**Comment by pghattas** [comment] 2022-06-04 15:14
Reading the forums, people using Blue Iris, Frigate, Synology and others are all having issues with their integrations after they upgraded to Protect 2.0.x.  Im curious if all of these integration solutions are all related to the second audio stream issue.

**Comment by pghattas** [comment] 2022-06-04 15:23
Another FYI, I read frigate has a workaround, they have a workaround by ignoring the audio stream completely.  Even prior protect 2.0, the webrtc plugin never played audio even though my cameras did have audio (which I was fine with).  If we can get a workaround to ignore the audio on the rtsp stream, that would be a good enough workaround for me.  (***sigghhh*** I wish I knew python)

**Comment by pghattas** [comment] 2022-06-04 15:31
Sorry for all the serial comments,  can anyone try to add "muted: true" (without quotes) to their lovelace for the webrtc camera to see if this is a workaround and report back?

**Comment by Boromore** [comment] 2022-06-04 17:04
Tried this already, but without luck.

**Comment by pghattas** [comment] 2022-06-04 17:15
> Tried this already, but without luck.

Thanks for confirming.

**Comment by MuttzNuttz** [comment] 2022-06-06 09:15
I have rolled protect back to 1.21.6 and restored from a backup (Pre 2.0) to get WebRTC displaying feeds in HA again.
I have also turned off Auto update for the unifi apps as a tempory measure until this is solved.
I also use [https://github.com/Anonymousdog/displaycameras] on a PI in my office and this was unaffected by the update to V2.0 of protect. Just thought I would add that for info as it does use the same rtsp streams.

**Comment by Haloooch** [comment] 2022-06-20 01:32
I can confirm I'm also being affected by this issue, going to hold off rolling back in the hope this one gets fixed soon.

**Comment by fahhome123** [comment] 2022-07-04 10:10
I have the same Problem with this.
After Update to Protect version > 2.0.0 this stops working.
Nothing on logs.
I using it on Home Assistant as HACS.

PLEASE fix it.

**Comment by AlexxIT** [comment] 2022-07-12 17:03
Someone needs to share your camera stream with me. It's better to contact with me in Telegram (same nickname)

**Comment by pghattas** [comment] 2022-07-13 10:08
Upgrade webrtc to version 2.3.1 and this is now working with Unifi Protect 2.0

**Comment by Boromore** [comment] 2022-07-13 11:01
Also no luck with 2.3.1
Even removed webrtc integration and reinstalled it.
![image](https://user-images.githubusercontent.com/89996595/178718730-a46f3a9d-febc-40f0-970e-cbb401deca35.png)
Nox I get this message.

**Comment by tech-byte** [comment] 2022-07-14 06:53
Unfortunately the mse: false work around didn't fix the problem for me:

Lovelace yaml
type: custom:webrtc-camera
url: rtsp://[IP]:7447/[UnifiGeneratedStreamID]
title: Testing
mse: false

**Comment by Boromore** [comment] 2022-07-14 07:25
This config works for me. Unifi protect and G4 doorbell.

type: custom:webrtc-camera
url: rtsp://[IP]:7447/[UnifiID]
poster: http://[IP]/snap.jpeg
muted: false
mse: false
webrtc: true

**Comment by Haloooch** [comment] 2022-07-14 07:34
I can also confirm the 'msc: false' is working for me if I use the webrct-camera card, unfortunately for me I use the frigate-card to display all my feeds :(

**Comment by MuttzNuttz** [comment] 2022-07-15 10:18
Just testing now using mse: false parameter and so far this is working on my setup.
WebRTC Camera V 2.3.1 
Protect V2.1.1

Unifi G4 Doorbell
G4 Bullets
G3 Bullets
G3 Flex
G3 Instant  & even G2 bullets all working based on the additional parameter being used.

**Comment by toxicsensibility** [comment] 2022-07-18 01:41
> Update: Appeared to be an issue with the setup. Reinstalled v2.3.1 and the below config now works correctly 👍
> 
> Lovelace yaml type: custom:webrtc-camera url: rtsp://[IP]:7447/[UnifiID] title: Testing mse: false

Hey I’m trying to figure this out and having trouble understanding what the “UnifiID” is. I was just going into Protect and grabbing the RTSPS url that it generated. I understand that rtsps does not work in webrtc. The missing piece in making the rtsp url for me is the “UnifiID”, could you please elaborate on what that is? Thanks

**Comment by Boromore** [comment] 2022-07-18 05:27
Modify the Unifi url
rtsps://IP:7441/UnifiID?enableSrtp
to
rtsp://IP:7447/UnifiID

**Comment by struz7** [comment] 2022-07-31 09:52
> You need to use `mse: false` setting for this cameras. Before I can find time to fix this bug. https://github.com/AlexxIT/WebRTC#configuration
> 
> I'll fix the problem in the next major version. But it may not be soon.
> 
> Also Unify has the wrong RTSP implementation for this case:
> 
> * They using same payload type (96) for both audio tracks. Not all clients can support it.
> * Also they added the video track last. Some players may have problems.
> * Also they used codec names in lowercase. Some players may have problems.
> 
> Let them know about the bugs, if it possible.
> 
> ```
> m=audio 0 RTP/AVP 96
> a=recvonly
> a=rtpmap:96 mpeg4-generic/48000/1
> a=control:trackID=0
> a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1188; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
> m=audio 0 RTP/AVP 96
> a=recvonly
> a=rtpmap:96 opus/48000/2
> a=control:trackID=1
> a=fmtp:96
> m=video 0 RTP/AVP 97
> a=recvonly
> a=control:trackID=2
> a=rtpmap:97 H264/90000
> a=fmtp:97 profile-level-id=4d4033; packetization-mode=1; sprop-parameter-sets=Z01AM42NQB4AIf/gLcBAQFAAAD6AAAu4CdoIhGo=,aO44gA==
> ```

Thanks @AlexxIT, I was able to resolve this with my G4 Doorbell and a Lovelace card.
But how do I add the mse setting when using the WebRTC "Create a link" service?

**Comment by AlexxIT** [comment] 2022-07-31 10:45
Try to add `&mse=false` to link.

**Comment by struz7** [comment] 2022-07-31 23:52
> Try to add `&mse=false` to link.

Thanks again @AlexxIT this has resolved my issue.

**Comment by TKpizza** [comment] 2022-08-04 14:02
Its working in the webrtc card for me now, but not the frigate card. Is there something they need to change?

**Comment by AlexxIT** [comment] 2022-08-06 03:57
Does someone have camera with two way audio? I wonder if UniFi support RTSP backchannel standard. You can check it with utility:
https://github.com/AlexxIT/rtsplog

**Comment by struz7** [comment] 2022-08-08 23:01
> Does someone have camera with two way audio? I wonder if UniFi support RTSP backchannel standard. You can check it with utility: https://github.com/AlexxIT/rtsplog

Hey mate, check out the below output from rtsplog:

`2022/08/09 08:56:41 RTSP/1.0 200 OK
CSeq: 1
Cache-Control: no-store
Date: Mon, 08 Aug 2022 22:56:41 UTC
Expires: Mon, 08 Aug 2022 22:56:41 UTC
Pragma: no-cache
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
Server: EvoStream Media Server (www.evostream.com)

2022/08/09 08:56:41 RTSP/1.0 200 OK
CSeq: 2
Cache-Control: no-store
Content-Base: rtsp://<REDACTED>:7447/VlrAZkULQZbnZ83Y/
Content-Length: 682
Content-Type: application/sdp
Date: Mon, 08 Aug 2022 22:56:41 UTC
Expires: Mon, 08 Aug 2022 22:56:41 UTC
Pragma: no-cache
Server: EvoStream Media Server (www.evostream.com)

v=0
o=- 35403 0 IN IP4 10.0.0.25
s=74ACB9012365_0
u=www.evostream.com
e=contact@evostream.com
c=IN IP4 <REDACTED>
t=0 0
a=recvonly
a=control:*
a=range:npt=now-
m=audio 0 RTP/AVP 96
a=recvonly
a=rtpmap:96 mpeg4-generic/48000/1
a=control:trackID=0
a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1188; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
m=audio 0 RTP/AVP 96
a=recvonly
a=rtpmap:96 opus/48000/2
a=control:trackID=1
a=fmtp:96
m=video 0 RTP/AVP 97
a=recvonly
a=control:trackID=2
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=4d4032; packetization-mode=1; sprop-parameter-sets=Z01AMo2NQBUAX/y4C3AQEBQAAA+gAALuAnaCIRqA,aO44gA==
2022/08/09 08:56:41 available tracks: [0xc000020440 0xc00001a210 0xc000050180]`

**Comment by AlexxIT** [comment] 2022-08-09 10:09
@struz7 Thanks! Unfortunately, there is no backchannel in response.

On Dahua cameras the response may be different if additional parameters are used in the RTSP link.

Do the cameras support the ONVIF protocol?

**Comment by struz7** [comment] 2022-08-09 23:10
> @struz7 Thanks! Unfortunately, there is no backchannel in response.
> 
> On Dahua cameras the response may be different if additional parameters are used in the RTSP link.
> 
> Do the cameras support the ONVIF protocol?

From what I have read, Ubiquiti does not support ONVIF

**Comment by AlexxIT** [comment] 2022-08-21 11:20
Check my new project. It may support multiple audio tracks . And Opus codec for audio.
https://github.com/AlexxIT/go2rtc

**Comment by pghattas** [comment] 2022-08-22 02:13
@AlexxIT very nice.  go2rtc is very fast and works great so far.   I do have a question about the config file.  How can I modify the config file when running in docker container?  Everytime I restart, the saved streams in the web api are gone and I was hoping I can make them persistent.

**Comment by AlexxIT** [comment] 2022-08-22 03:11
`-v ~/go2rtc.yaml:/config/go2rtc.yaml`

**Comment by shgubar** [comment] 2022-08-22 08:36
> Check my new project. It may support multiple audio tracks . And Opus codec for audio. https://github.com/AlexxIT/go2rtc

Please help. How to use this app via custom_integration?

**Comment by pghattas** [comment] 2022-08-22 10:24
Worked.Thank you

**Comment by pghattas** [comment] 2022-08-22 10:24
> `-v ~/go2rtc.yaml:/config/go2rtc.yaml`

Worked. Thank you.

**Comment by AlexxIT** [comment] 2022-08-22 10:58
Can you hear sound with go2rtc? Is opus from UniFi works fine?

**Comment by AlexxIT** [comment] 2023-01-20 16:06
Should be fixed in v3

**Closed by AlexxIT** 2023-01-20 16:06 UTC
Labels: bug, go2rtc
