### ISSUE TITLE
Error during setup of component (core-2021.12.0)

### ISSUE THREAD

**Issue by r3mcos3** [AlexxIT/WebRTC#156] opened 2021-11-10 07:43 UTC
## System Health

version | core-2021.12.0.dev20211110
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.70
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4952
Installed Version | 1.16.0
Stage | running
Available Repositories | 965
Installed Repositories | 8

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 22, 2021, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0.dev20211104
-- | --
update_channel | dev
supervisor_version | supervisor-2021.11.dev0901
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), SSH & Web Terminal (9.0.1), Home Assistant Google Drive Backup (0.105.2), MariaDB (2.4.0), ESPHome (dev) (dev)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 7
views | 4
mode | storage

</details>

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 08:37:12 (1 occurrences)
Last logged: 08:37:12

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

```

**Comment by Ballyhoot** [comment] 2021-11-29 17:43
I have this same exact issue. Mine is on a RPi4. I just moved HA to Docker.  WebRTC worked fine when using the HA OS.

**Comment by sean-m-sullivan** [comment] 2021-11-30 04:14
Same issue and I'm using This 
<h1 class="card-header"><div class="card-header-text">System Health
          </div>
          <ha-button-menu corner="BOTTOM_START" slot="toolbar-icon">
            <ha-icon-button slot="trigger"></ha-icon-button>
            
            
          </ha-button-menu>
        </h1>
        <div class="card-content">
          

Version | core-2021.12.0.dev20211129
-- | --
Installation Type | Home Assistant OS
Development | true
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.78
CPU Architecture | x86_64
Timezone | America/New_York

</div>

**Comment by jscherry** [comment] 2021-12-04 02:03
Same issue after updating to 2021.12 beta. Worked with all other previous versions of HA. Running HA OS supervised on Blue (Odroid). Logs below:
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 7:51:20 PM (1 occurrences)
Last logged: 7:51:20 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

I Tried unisntalling and re-installing the integration, rebooted core and server?

**Comment by AlexxIT** [comment] 2021-12-06 04:21
Fixed in latest master version

**Comment by sean-m-sullivan** [comment] 2021-12-07 04:41
Have installed master version and encountered the same issue.

**Comment by Delta1977** [comment] 2021-12-07 15:01
same here:
## System Health

version | core-2021.12.0b2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4712
Installed Version | 1.18.0
Stage | running
Available Repositories | 913
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | beta
supervisor_version | supervisor-2021.12.0
docker_version | 20.10.9
disk_total | 63.0 GB
disk_used | 18.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), InfluxDB (4.3.0), Nginx Proxy Manager (0.11.0), SSH & Web Terminal (9.1.1), Node-RED (10.2.0), AirSonos (3.2.0), Grafana (7.3.2), WireGuard (0.6.0), Glances (0.14.0), MariaDB (2.4.0), Studio Code Server (3.7.0), Mosquitto broker (6.0.1), ESPHome (2021.11.4), Duck DNS (1.14.0), Zigbee2mqtt (1.22.1-1), ADS-B Multi-Portal Feeder (0.1.32), motionEye (0.16.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 3
mode | storage

</details>

**Comment by AlexxIT** [comment] 2021-12-07 17:06
@sean-m-sullivan show error log from master version

**Comment by jine** [comment] 2021-12-10 02:47
Same issue here.

`Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: December 9, 2021, 21:03:40 (1 occurrences)
Last logged: December 9, 2021, 21:03:40

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'`

**Comment by LordNex** [comment] 2021-12-12 07:48
Ok, I can confirm that if you select the "master" branch, not the version numbers. it does resolve the issue. Im running ESXi 7.0 HA OVA on an i5 laptop.

**Comment by rudizl** [comment] 2021-12-12 18:54
Same problem with core-2021.12
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 20:34:41 (1 occurrences)
Last logged: 20:34:41

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by r3mcos3** [comment] 2021-12-12 19:14
in hacs re-download but then choose master version

**Comment by shlomosv1** [comment] 2021-12-12 21:42
error for webrtc with core-2021.12.0 problem solved and works fine when : 
 do hacs re-download , then choose master version. 
thanks.

**Comment by AlexxIT** [comment] 2021-12-13 09:07
I wonder when people will stop creating duplicates

**Comment by r3mcos3** [comment] 2021-12-13 14:38
then don't update, 
the creator off this component has to do this in his free time I guess, you can't decide over his free time.

maybe you can fix it yourself, it's open source.

**Comment by htmltiger** [comment] 2021-12-13 14:47
> then don't update, the creator off this component has to do this in his free time I guess, you can't decide over his free time.
> 
> maybe you can fix it yourself, it's open source.
I am fine with the master branch.
But in this case the creator spent more time replying to (above 15) issues that can be avoided in future by a new release.

**Comment by sermayoral** [comment] 2021-12-13 17:08
> I wonder when people will stop creating duplicates

I would release a new version with the fix. In that way I'm sure people would stop creating duplicates :-)

**Comment by AlexxIT** [comment] 2021-12-13 17:55
@htmltiger how much time does it take the user to skip the request to "search for an existing issue and not create duplicates"?

**Comment by Sholofly** [comment] 2021-12-13 17:56
Isn't there a way to recommend similar issues automatically, before submitting an issue?

**Comment by htmltiger** [comment] 2021-12-13 18:14
Hmm, I searched for 'allow_cors' in all issues and found the answer but not everyone is good at searching or looking in the pinned issue.

For you it would takes less keystrokes to push the release then closing new issues that pop every hour.
`Releases > Draft a new release > enter version / tag > Publish release`

> @htmltiger how much time does it take the user to skip the request to "search for an existing issue and not create duplicates"?

**Comment by AlexxIT** [comment] 2021-12-14 04:22
If it teaches anyone to respect other people's work, I am ready to spend my time on closing such tasks.

Fixed in [v2.2.0](https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0).

**Closed by AlexxIT** 2021-12-14 04:22 UTC
Labels: bug

**Comment by chatainsim** [comment] 2021-12-14 08:05
Thank you @AlexxIT for your time and this great component.

**Comment by htmltiger** [comment] 2021-12-14 12:52
> If it teaches someone to respect other people's work, I am ready to spend my time on closing such tasks.
> 
> Fixed in [v2.2.0](https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0).

Thank you @AlexxIT
Its loud and clear, don't change the keys without deprecation.

---
_Originally posted by @balloob in https://github.com/home-assistant/core/pull/59360#discussion_r744936326_
Can we make these keys a bit more descriptive

- `allow_cors` -> `allow_all_cors`
- `add_cors` -> `allow_configured_cors`

**Comment by ONBET** [comment] 2022-03-09 04:32
Me too, there is no 2.2.0 in store , master branch not working too

**Comment by lone-cloud** [comment] 2022-03-12 03:26
I re-downloaded master and the error went away. You should ensure that your error matches the trace stack from https://github.com/AlexxIT/WebRTC/issues/156#issuecomment-985946192 otherwise you could be seeing a different error.

Kind of frustrating that the project owner is not putting out new releases in github, but instead tagging commits in git which is useless to us who pull this repo from ha.

**Comment by DaveDee** [comment] 2022-03-16 16:18
fresh install core-2022.3.4, trying to set up some tuya camera

```
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera ([documentation](https://github.com/AlexxIT/WebRTC), [issues](https://github.com/AlexxIT/WebRTC/issues))
First occurred: 19:07:15 (1 occurrences)
Last logged: 19:07:15

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
```

**Comment by wifispray** [comment] 2022-03-21 18:09
Is this not working still? I get an error in after the HACS install. 

Success!
Created configuration for WebRTC Camera.

The integration could not be loaded, try to restart Home Assistant.

**Comment by howelljiang** [comment] 2022-03-22 12:04
## System Health

version | core-2022.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 4390
Installed Version | 1.23.0
Stage | running
Available Repositories | 1080
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 118.3 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.5.1), Node-RED (11.1.0), Mosquitto broker (6.0.1), Terminal & SSH (9.3.0), Zigbee2mqtt (1.23.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 2
mode | storage

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 12
added_devices | 6

</details>

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera ([documentation](https://github.com/AlexxIT/WebRTC), [issues](https://github.com/AlexxIT/WebRTC/issues))
First occurred: 19:56:56 (1 occurrences)
Last logged: 19:56:56

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by homeoneautomacao** [comment] 2022-04-05 20:21
I don't know if it's related to this problem but I had to return my HA version to 2022.2.9, because the 2022.3.1 version together with any version of webrtc, using android, the internal url doesn't work, it keeps giving a message that the webrtc is not installed.

**Comment by maxromanovsky** [comment] 2022-04-10 11:38
@AlexxIT it would be awesome if you could push a new release (`v2.2.0`) to GitHub

**Comment by homeoneautomacao** [comment] 2022-04-19 13:34
who use lovelace: yaml, change to storage..... for me solve the problem "element doesn´t exist:custom:webrtc" on the app android or iphone

**Comment by manj9501** [comment] 2022-04-27 10:34
Hey @AlexxIT, can you please release v2.2.0 in the HACS store? Thanks in advance!

**Comment by maxromanovsky** [comment] 2022-04-27 20:43
@manj9501 there's `v2.3.0` already, and it's properly published: https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0

**Comment by manj9501** [comment] 2022-04-27 21:49
My bad! 
Should have used the 'Update Information' option after downloading the HACS integration.

Thanks much!
